server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviedbexample
    username: mytestuser
    password: My6$Password
#    testWhileIdle: true
#    validationQuery: SELECT 1
###################################### MyBatis 配置######################################
mybatis:
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true


